name: "Contexts Example"

on: [push, pull_request]

jobs:
  context_job:
    runs-on: ubuntu-latest

    steps:
      env:
        MY_ACTION: ${{ github.action }}
      name: "Show context value"
      run: |
        echo "The action name is $MY_ACTION"