name: "Contexts Example"

on: [push, pull_request]

jobs:
  context_job:
    runs-on: ubuntu-latest

    steps:
      - name: "Show context value"
        env:
          MY_ACTION: ${{ github.action }}
          MY_ACTOR: ${{ github.actor }}
        run: |
          echo "The action name is $MY_ACTION"
          echo "The actor is $MY_ACTOR"