name: "Dependant job example"

on: [push, pull_request]

jobs:
  old_job:
    runs-on: ubuntu-latest
    steps:
      - name: "Old job step"
        run: echo "hello"
  new_job:
    runs-on: ubuntu-latest
    needs: old_job
    steps:
      - name: "New job step 1"
        run: echo "world"