name: "Workflow componenets"

on: [push, pull_request]

jobs:
  my_job:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2

      - name: "group logging"
        run: |
          echo "::group::My Group Message"
          echo "Msg 1"
          echo "Msg 2"
          echo "::endgroup::"
      - name: "step 1"
        runs: |
          echo "MY_VAL-hello" >> $GITHUB_ENV
      -name: "step 2"
        runs: |
          echo "$MY_VAL"